In [1]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import os

In [2]:
LTC_BINARY = '../data/ltc_matrices/ltc_matrix_binary_mm4.tsv'

#print(os.listdir('Data/ltc_matrices'))

ltc_patients = pd.read_csv(LTC_BINARY, sep = '\t')

ltc_patients.tail(5)

,patient_id,dermatitis,erectile_dysfunction,OA,pri_skin,skin_ulcer,female_genital_prolapse,fracture_hip,obesity,spondylosis,...,cerebral_palsy,pri_mesothelioma,pri_brain,thala,sick_sinus,ADHD,juv_arth,downs,entero_arthro,SARS_CoV2
143163,6024736,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
143164,6024745,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
143165,6024791,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
143166,6024800,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
143167,6024824,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
dictionary_of_patients = dict()

patients = ltc_patients['patient_id'].unique()
ltcs = ltc_patients.drop('patient_id', axis = 1)
index = 0

#Iterate through patients
for patient in patients:
    
    #Start with empty list of LTCs for each patient
    patient_ltcs = []
    
    #Iterate through each LTC for patient
    for ltc in ltcs:
        
        #Check if patient has LTC or not
        if ltc_patients.at[index, ltc] == 1:
            
            #If LTC present, add to list of patient LTCs
            patient_ltcs.append(ltc)   
    
    #Add list of patient LTCs to dictionary of patients        
    dictionary_of_patients[patient] = patient_ltcs
    
    #Increment index by 1
    index+=1

In [5]:
print(dictionary_of_patients[6024824])

['dermatitis', 'skin_ulcer', 'enthesopathy', 'alcohol_depend', 'sinusitis']